<?php
ini_set("allow_url_fopen",1);
switch (@parse_url($_SERVER['REQUEST_URI'])['path']) {
    case '/';
    require 'index.php';
    break;
	case '/index.php';
	require 'index.php';
	break;
    case '/dashboard.php';
    require 'dashboard.php';
    break;
    case "/AddBanner.php";
    require __DIR__ .'/AddBanner.php';
    break;
    case "/AddBranches.php";
    require __DIR__ .'/AddBranches.php';
    break;
    case "/AddInfo.php";
    require __DIR__ .'/AddInfo.php';
    break;
    case "/addItemList.php";
    require __DIR__ .'/addItemList.php';
    break;
    case "/AddItemPage.php";
    require __DIR__ .'/AddItemPage.php';
    break;
	case "/AddStock.php";
    require __DIR__ .'/AddStock.php';
    break;
	case "/AddStore.php";
    require __DIR__ .'/AddStore.php';
    break;
	case "/AllOrderDescription.php";
    require __DIR__ .'/AllOrderDescription.php';
    break;
	case "/AllOrderDescriptionByDate.php";
    require __DIR__ .'/AllOrderDescriptionByDate.php';
    break;
	case "/create_del.php";
    require __DIR__ .'/create_del.php';
    break;
	case "/createItems.php";
    require __DIR__ .'/createItems.php';
    break;
	case "/icons.php";
    require __DIR__ .'/icons.php';
    break;
	case "/ItemDesc.php";
    require __DIR__ .'/ItemDesc.php';
    break;
	case "/Itemslist.php";
    require __DIR__ .'/Itemslist.php';
    break;
	case "/ListAddress.php";
    require __DIR__ .'/ListAddress.php';
    break;
	case "/map.php";
    require __DIR__ .'/map.php';
    break;
	case "/MapsAddress.php";
    require __DIR__ .'/MapsAddress.php';
    break;
	case "/notifications.php";
    require __DIR__ .'/notifications.php';
    break;
	case "/OrderDescription.php";
    require __DIR__ .'/OrderDescription.php';
    break;
	case "/OrderDetailsTwo.php";
    require __DIR__ .'/OrderDetailsTwo.php';
    break;
	case "/SelectBranchesAddress.php";
    require __DIR__ .'/SelectBranchesAddress.php';
    break;
	case "/SelectStoreAddress.php";
    require __DIR__ .'/SelectStoreAddress.php';
    break;
	case "/SettingCoupon.php";
    require __DIR__ .'/SettingCoupon.php';
    break;
	case "/SettingPoint.php";
    require __DIR__ .'/SettingPoint.php';
    break;
	case "/SortOrder.php";
    require __DIR__ .'/SortOrder.php';
    break;
	case "/SubItem.php";
    require __DIR__ .'/SubItem.php';
    break;
	case "/tables.php";
    require __DIR__ .'/tables.php';
    break;
	case "/TestPage.php";
    require __DIR__ .'/TestPage.php';
    break;
	case "/typography.php";
    require __DIR__ .'/typography.php';
    break;
	case "/user.php";
    require __DIR__ .'/user.php';
    break;


    
    defualt:
    http_response_code(404);
    echo @parse_url($_SERVER['REQUEST_URI'])['path'];
    exit('Not Found');
}
